
  final List<Map> museum = [
    {
      "name": "المتحف الحربي القومي",
      "location": "صلاح سالم، قلعة، قسم الخليفة‬",
      "Date": " من 9ص:5م ",
      "Cafe": "كبابجى المنشاوى -أبو سليمان مكرونه -كنتاكى المقطم -سيلنترو",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف جاير أندرسون",
      "location": "أحمد بن طولون, السيدة زينب",
      "Date": " من 9ص:5م ",
      "Cafe": "أسماك بلية -المهندس -كافية سرايا الجزيرة -D.Cappuccino",
      "logoText": "images/park.jpg",
      "price": "5 LE",
    },
    {
      "name": "المتحف القبطى",
      "location": "	ماري جرجس، كوم غراب، حي مصر القديمة",
      "Date": " من 9ص:5م ",
      "Cafe": "Volo's Cafe -Resturant & Cafe Al Khan -مطعم تاچوري",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الفن الإسلامي بالقاهرة",
      "location": "شارع بور سعيد، الدرب الأحمر",
      "Date": " من 9ص:5م ",
      "Cafe": "انى فينو -الأصيل -زيتوني -سيلنترو -كافيه كوزمو",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف قصر عابدين",
      "location": "شارع جمعه عابدين، ميدان الجمهورية، رحبة عابدين",
      "Date": " من 9ص:3م ",
      "Cafe": "Oldish(Restaurant & Cafe)- كنتاكى -مطعم الجمهورية",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "المتحف الجيولوجى المصرى",
      "location": "الخوخة والقناية، حي مصر القديمة",
      "Date": " من 9ص:5م ",
      "Cafe": "سيلنترو -سى هورس كلوب -Tavola Restaurant and Lounge",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "المتحف القومي للحضارة",
      "location": "الديورة، حي مصر القديمة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "ماكدونالدز -عنتر الكبابجى -Resturant & Cafe Al Khan",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف ام كلثوم",
      "location": "حي مصر القديمة، محافظة القاهرة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "مطعم تاچوري -ماكدونالدز -Old Cairo Restaurant & Cafe",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "المتحف المصري",
      "location": "Tahrir Square rd Tahrir Square‬",
      "Date": " من 9ص:5م ",
      "Cafe": "مطعم تبوله -بانى فينو -Oldish ( Restaurant & Cafe )",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "قصر الأمير محمد علي بالمنيل",
      "location": "السرايا، المنيل، حي مصر القديمة",
      "Date": " من 9ص:4م ",
      "Cafe": "عنتر الكبابجى -العمدة للمشويات -Charlie Chimney Cake",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف محمود خليل",
      "location": "كافور، الدقي، الدقى، الجيزة",
      "Date": " من 9ص:4م ",
      "Cafe": "باب اليمن -لاتينو مطعم وكافيه الدقي -طازه -الزعيم",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "المتحف الزراعي",
      "location": "كوبري 6 اكتوبر، الدقى",
      "Date": " من 9ص:4م ",
      "Cafe": "Signature restaurant & cafe- أم حسن",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الخزف الاسلامى",
      "location": "الشيخ المرصفي، عمر الخيام، الزمالك",
      "Date": " من 9ص:4م ",
      "Cafe": "Garden Promenade Café -مطعم توسكانا",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف النسيج المصري",
      "location": "المعز لدين الله الفاطمي، الجمالية، قسم الجمالية",
      "Date": " من 9ص:5م ",
      "Cafe": "ساقيه بيت القاضى -اليمنى - Tekiyt Khan Khatun",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "مركز الحرف بالفسطاط",
      "location": "الإمام مالك، الديورة، حي مصر القديمة",
      "Date": " من 9ص:4م ",
      "Cafe": "Bonne Soirée Restaurants -عنتر الكبابجى -فاطاطرى القاهرة",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "الجمعية الجغرافية المصرية",
      "location": "109 شارع القصر العيني، مدخل مجلس النواب",
      "Date": " من 9ص:4م ",
      "Cafe": "Oldish ( Restaurant & Cafe ) - تبوله - باني فينو",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "قصر الفنون",
      "location": "Ard El Opera، EL GEZIRAH، الزمالك‬",
      "Date": " من 9ص:4م ",
      "Cafe": "المطعم الدوار 360 -نايل سيتي العائمة -زيتوني",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف مصطفى كامل",
      "location": "الديورة، حي مصر القديمة، محافظة القاهرة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "كسكسي ابو احمد -Resturant & Cafe Al Khan -عنتر الكبابجى",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الطفل",
      "location": "34 أبو بكر الصديق، البستان، قسم مصر الجديدة",
      "Date": " من 9ص:4م ",
      "Cafe": "حضر موت -مطعم أنس الدمشقي",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الفن المصري الحديث",
      "location": "الزمالك، محافظة القاهرة",
      "Date": " من 9ص:4م ",
      "Cafe": "Le Deck -By Laurent Peugeot- بانى فينو",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الشرطة القومي",
      "location": "ممر داخل قلعة صلاح الدين، الأباجية، قسم الخليفة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "أبو سليمان مكرونه_ كبابجى المنشاوى",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف علم الحيوان",
      "location": "قسم الحيوان، داخلي - جامعة القاهرة، أولى، الجيزة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "Hayda Lebanese Restaurant- مطعم سان جورج",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
    {
      "name": "متحف الشمع بحلوان",
      "location": "منصور، قسم حلوان، محافظة القاهرة‬",
      "Date": " من 9ص:4م ",
      "Cafe": "ابوصلاح _ كاب تشكن _ بيتزا وكريب وعصاير القنبلة",
      "logoText": "images/musem.jpg",
      "price": "5 LE",
    },
  ];

